@host = {{$dotenv WORKER_URL}}

###
POST {{host}}/admin/init_upstreams
Authorization: Basic admin {{$dotenv ADMIN_PASSWORD}}

###
POST  {{host}}/admin/clear_storage
Authorization: Basic admin {{$dotenv ADMIN_PASSWORD}}

###
GET {{host}}/admin/chains
Authorization: Basic admin {{$dotenv ADMIN_PASSWORD}}


###
GET {{host}}/admin/upstreams
Authorization: Basic admin {{$dotenv ADMIN_PASSWORD}}

###
GET {{host}}/admin/stats    
Authorization: Basic admin {{$dotenv ADMIN_PASSWORD}}

### 
POST {{host}}/bsc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "eth_syncing",
  "params": [],
  "id": 1
}