@host = {{$dotenv WORKER_URL}}

###
POST {{host}}/admin/init_upstreams

###
DELETE {{host}}/admin/clear_storage

###
GET {{host}}/admin/chains


###
GET {{host}}/admin/upstreams

###
GET {{host}}/admin/stats    

### 
POST {{host}}/bsc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "eth_syncing",
  "params": [],
  "id": 1
}